data_home = "D:\\Users\\maxwelfreitas\\OneDrive - ANATEL\\AppData\\schwordcloud\\datasets"

[cloud]
cloud_annotation_get_folder = "D:\\Users\\maxwelfreitas\\ANATEL\\InovaFiscaliza - DataHub - GET\\SCH"
cloud_annotation_post_folder = "D:\\Users\\maxwelfreitas\\ANATEL\\InovaFiscaliza - DataHub - POST\\SCH"

[credentials]
credentials_file = "D:\\Users\\maxwelfreitas\\OneDrive - ANATEL\\credentials.toml"

[search_params]
category = 2
grace_period = 120
shuffle = true
